version: '3.8'

services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: manga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    ports:
      - "9000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/manga
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:9000"

volumes:
  postgres_data: